steps:
  - name: "Deploy Nginx to Kubernetes"
    command: |
      kubectl apply -f k8s/
      echo "\nWaiting for deployment to be ready..."
      kubectl rollout status deployment/nginx-deployment --timeout=300s
      echo "\nDeployment status:"
      kubectl get pods -l app=nginx
      echo "\nService status:"
      kubectl get service nginx-service
    agents:
      queue: kubernetes
    plugins:
      - docker#v3.1.0:
          image: "k8s.gcr.io/kubectl:v1.28.0"
          always-pull: true
