steps:
  - label: ":docker: Build Custom Buildkite+Namespace Image"
    key: build-image
    agents:
      queue: kubernetes
    command: |
      # Build the custom image
      docker build -f Dockerfile.buildkite-namespace -t buildkite-namespace:${BUILDKITE_BUILD_NUMBER} .
      
      # Tag for registry (update with your registry)
      docker tag buildkite-namespace:${BUILDKITE_BUILD_NUMBER} ghcr.io/mykematt/buildkite-namespace:${BUILDKITE_BUILD_NUMBER}
      docker tag buildkite-namespace:${BUILDKITE_BUILD_NUMBER} ghcr.io/mykematt/buildkite-namespace:latest
      
      # Push to registry (you'll need to authenticate first)
      # docker push ghcr.io/mykematt/buildkite-namespace:${BUILDKITE_BUILD_NUMBER}
      # docker push ghcr.io/mykematt/buildkite-namespace:latest
      
      echo "Image built successfully!"
      echo "Next steps:"
      echo "1. Authenticate to your container registry"
      echo "2. Push the image"
      echo "3. Update Helm values to use this image"
