steps:
  - label: ":docker: Build & Push via Namespace"
    agents:
      queue: linux
    env:
      NS_IMAGE_NAME: "namespace-app"
      NS_IMAGE_TAG: "${BUILDKITE_BUILD_NUMBER}"
    commands:
      - set -euo pipefail
      - echo "--- :docker: Build image locally"
      - docker build -t "namespace-app:${NS_IMAGE_TAG}" .
    plugins:
      - docker-image-push#54d3d9e:
          provider: namespace
          image: "namespace-app"
          tag: "$NS_IMAGE_TAG"
          namespace:
            tenant-id: "tenant_uabmve166l99o"
            nsc-binary: "/home/olabuildkite/.ns/bin/nsc"
            auth-method: aws-cognito
            aws-cognito:
              region: "us-east-1"
              identity-pool: "217947c4-e20e-4315-97f8-08e9a14c8dfb"
