steps:
  - label: ":docker: Build & Push via Namespace"
    agents:
      queue: linux
    env:
      NS_IMAGE_NAME: "namespace-app"
      NS_IMAGE_TAG: "latest"
      PATH: "/home/olabuildkite/.ns/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    command: |
      set -euo pipefail
      docker build -t "namespace-app:latest" .
      docker images namespace-app:latest
    plugins:
      - docker-image-push#54d3d9e:
          provider: namespace
          image: "namespace-app"
          tag: "latest"
          namespace:
            tenant-id: "uabmve166l99o"
            nsc-binary: "/home/olabuildkite/.ns/bin/nsc"
            auth-method: aws-cognito
            aws-cognito:
              region: "us-east-1"
              identity-pool: "217947c4-e20e-4315-97f8-08e9a14c8dfb"