steps:
  - label: ":docker: Build & Push via Namespace"
    agents:
      queue: kubernetes
    env:
      NS_IMAGE_NAME: "namespace-app"
      NS_IMAGE_TAG: "${BUILDKITE_BUILD_NUMBER}"
    plugins:
      - docker-image-push#54d3d9e:
          provider: namespace
          image: "nscr.io/tenant_uabmve166l99o/namespace-app"
          tag: "${NS_IMAGE_TAG}"
          namespace:
            tenant-id: "tenant_uabmve166l99o"
            auth-method: aws-cognito
            aws-cognito:
              region: "us-east-1"
              identity-pool: "217947c4-e20e-4315-97f8-08e9a14c8dfb"
    commands:
      - set -euo pipefail
      - echo "--- :docker: Building image locally"
      - docker build -t "nscr.io/tenant_uabmve166l99o/${NS_IMAGE_NAME}:${NS_IMAGE_TAG}" .
