steps:
  - label: ":docker: Build & Push via Namespace"
    agents:
      queue: linux
    command: |
      set -euo pipefail
      docker build -t "namespace-app:latest" .
      docker images namespace-app:latest
    plugins:
      - docker-image-push#54d3d9e:
          provider: namespace
          image: "namespace-app"
          tag: "latest"
          namespace:
            tenant-id: "tenant_uabmve166l99o"
            nsc-binary: "/home/olabuildkite/.ns/bin/nsc"
            auth-method: aws-cognito
            aws-cognito:
              region: "us-east-1"
              identity-pool: "217947c4-e20e-4315-97f8-08e9a14c8dfb"