# pipeline.yml
steps:
- name: Hello from a container with more resources
  command: echo Hello World!
  plugins:
  - kubernetes:
      sidecars:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 500m
            memory: 64Mi
          limits:
            memory: 128Mi
      podSpecPatch:
        containers:
        - name: container-0    # <-- Specify exactly as `container-0`.
          resources:           #     Currently under experimentation to make this more ergonomic.
            requests:
              cpu: 1000m
              memory: 50Mi
            limits:
              memory: 1Gi
