steps:
  - label: ":docker: Verify installations and build with Namespace"
    agents:
      queue: kubernetes
      
    command: |
      echo "=== Verifying installations ==="
      echo "Docker version:"
      docker --version
      
      echo ""
      echo "Docker Buildx version:"
      docker buildx version
      
      echo ""
      echo "Namespace CLI (nsc):"
      ls -la /root/.ns/bin/nsc
      
      echo ""
      echo "Buildkite Agent:"
      buildkite-agent --version
      
      echo ""
      echo "Bash location:"
      which bash
      ls -la /usr/local/bin/bash || echo "No symlink at /usr/local/bin/bash"
      
      echo ""
      echo "=== All dependencies verified! ==="
      
      echo ""
      echo "=== Starting Namespace build ==="
      
      # Get Buildkite OIDC token
      OIDC_TOKEN=$(buildkite-agent oidc request-token --audience federation.namespaceapis.com)
      echo "OIDC token obtained"
      
      # Exchange for Namespace credentials
      nsc auth exchange-oidc-token --token "$OIDC_TOKEN" --tenant_id tenant_uabmve166l99o
      echo "Namespace credentials exchanged"
      
      # Configure Docker BuildX to use Namespace
      nsc docker buildx setup --background --use
      echo "Namespace buildx configured"
      
      # Build and push to Namespace registry
      docker buildx build --builder nsc-remote \
        -t nscr.io/uabmve166l99o/test-app:${BUILDKITE_BUILD_NUMBER} \
        --push \
        .
      
      echo ""
      echo "=== Build complete! ==="
