steps:
  - label: ":docker: E2E Test - Build Multi-Platform Image with Namespace"
    agents:
      queue: kubernetes
      
    command: |
      set -euo pipefail
      
      echo "=== Step 1: Authenticate with Namespace using AWS Cognito ==="
      
      # Exchange AWS credentials for Namespace token via Cognito
      echo "Authenticating via AWS Cognito Identity Pool..."
      /root/.ns/bin/nsc auth exchange-aws-cognito-token \
        --aws_region us-east-1 \
        --identity_pool 217947c4-e20e-4315-97f8-08e9a14c8dfb \
        --tenant_id tenant_uabmve166l99o
      echo "✓ Authenticated with Namespace workspace"
      
      echo ""
      echo "=== Step 2: Configure Docker Buildx for Namespace ==="
      
      # Set up Namespace as a Docker Buildx builder
      /root/.ns/bin/nsc docker buildx setup --background --use
      echo "✓ Namespace remote builder configured"
      
      # Verify builder is available
      echo ""
      echo "Available builders:"
      docker buildx ls
      
      echo ""
      echo "=== Step 3: Build with Namespace Remote Builders ==="
      echo "Building: Dockerfile (helm-kubectl + AWS CLI)"
      echo "Platforms: linux/amd64, linux/arm64"
      echo "Registry: nscr.io/uabmve166l99o"
      echo ""
      
      # Build existing Dockerfile for both amd64 and arm64 using Namespace remote builders
      docker buildx build \
        --builder nsc-remote \
        --platform linux/amd64,linux/arm64 \
        -f Dockerfile \
        -t nscr.io/uabmve166l99o/helm-kubectl-aws:$${BUILDKITE_BUILD_NUMBER} \
        -t nscr.io/uabmve166l99o/helm-kubectl-aws:latest \
        --push \
        .
      
      echo ""
      echo "=== ✓ E2E Test Complete! ==="
      echo ""
      echo "✓ OIDC authentication successful"
      echo "✓ Namespace remote builders configured"
      echo "✓ Multi-platform build successful (amd64 + arm64)"
      echo "✓ Image pushed to Namespace registry"
      echo ""
      echo "Images available at:"
      echo "  • nscr.io/uabmve166l99o/helm-kubectl-aws:$${BUILDKITE_BUILD_NUMBER}"
      echo "  • nscr.io/uabmve166l99o/helm-kubectl-aws:latest"
      echo ""
      echo "View build details: https://cloud.namespace.so/workspace/builds"
