steps:
  - label: ":docker: Test Basic Setup"
    agents:
      queue: kubernetes
    command: |
      echo "Docker version:"
      docker --version
      echo "Buildx version:"
      docker buildx version
      echo "Namespace CLI:"
      /root/.ns/bin/nsc --help | head -5
      echo "Success!"
