steps:
  - label: ":docker: Build with Namespace Remote Builders"
    agents:
      queue: kubernetes
    command: |
      # Install Docker and dependencies
      apt-get update
      apt-get install -y ca-certificates curl
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      apt-get update
      apt-get install -y docker-ce docker-ce-cli docker-buildx-plugin
      
      # Install Namespace CLI
      curl -fsSL https://get.namespace.so/cloud/install.sh | sh
      
      # Add nsc to PATH
      export PATH="/root/.ns/bin:$PATH"
      
      # Verify installations
      which docker
      which nsc
      docker --version
      nsc --version
      
      # Get Buildkite OIDC token
      OIDC_TOKEN=$(buildkite-agent oidc request-token --audience federation.namespaceapis.com)
      
      # Exchange for Namespace credentials
      nsc auth exchange-oidc-token --token "$OIDC_TOKEN" --tenant_id tenant_uabmve166l99o
      
      # Configure Docker BuildX to use Namespace
      nsc docker buildx setup --background --use
      
      # Build and push to Namespace registry
      docker buildx build --builder nsc-remote \
        -t nscr.io/uabmve166l99o/test-app:${BUILDKITE_BUILD_NUMBER} \
        --push \
        .
    plugins:
      - kubernetes:
          podSpec:
            initContainers:
              - name: setup-bash
                image: ubuntu:22.04
                command: ["/bin/sh", "-c"]
                args:
                  - |
                    mkdir -p /usr/local/bin
                    cat > /usr/local/bin/bash << 'EOF'
                    #!/bin/sh
                    exec /bin/bash -c "$@"
                    EOF
                    chmod +x /usr/local/bin/bash
                volumeMounts:
                  - name: usr-local-bin
                    mountPath: /usr/local/bin
            containers:
              - name: main
                image: ubuntu:22.04
                volumeMounts:
                  - name: usr-local-bin
                    mountPath: /usr/local/bin
            volumes:
              - name: usr-local-bin
                emptyDir: {}
