steps:
  - label: ":docker: Build with Namespace Remote Builders"
    agents:
      queue: kubernetes
    command: |
      # Set up PATH to include all necessary binaries
      export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/root/.ns/bin:$PATH"
      
      # Verify what's available
      echo "=== Checking available commands ==="
      which curl || echo "curl not found"
      which docker || echo "docker not found"
      which buildkite-agent || echo "buildkite-agent not found"
      
      # Install Namespace CLI
      curl -fsSL https://get.namespace.so/cloud/install.sh | sh
      
      # Verify installations after nsc install
      echo "=== After nsc installation ==="
      which nsc || echo "nsc not found"
      which docker || echo "docker not found"
      
      # Get Buildkite OIDC token
      OIDC_TOKEN=$(buildkite-agent oidc request-token --audience federation.namespaceapis.com)
      
      # Exchange for Namespace credentials
      /root/.ns/bin/nsc auth exchange-oidc-token --token "$OIDC_TOKEN" --tenant_id tenant_uabmve166l99o
      
      # Configure Docker BuildX to use Namespace
      /root/.ns/bin/nsc docker buildx setup --background --use
      
      # Build and push to Namespace registry
      docker buildx build --builder nsc-remote \
        -t nscr.io/uabmve166l99o/test-app:${BUILDKITE_BUILD_NUMBER} \
        --push \
        .
    plugins:
      - kubernetes:
          podSpec:
            initContainers:
              - name: setup-bash
                image: docker:latest
                command: ["/bin/sh", "-c"]
                args:
                  - |
                    mkdir -p /usr/local/bin
                    cat > /usr/local/bin/bash << 'EOF'
                    #!/bin/sh
                    exec /bin/sh -c "$@"
                    EOF
                    chmod +x /usr/local/bin/bash
                volumeMounts:
                  - name: usr-local-bin
                    mountPath: /usr/local/bin
            containers:
              - name: main
                image: docker:latest
                volumeMounts:
                  - name: usr-local-bin
                    mountPath: /usr/local/bin
            volumes:
              - name: usr-local-bin
                emptyDir: {}
