steps:
  - label: ":test_tube: Test 1 - Simple wrapper with vector interposer"
    agents:
      queue: "kubernetes"
    plugins:
      - kubernetes:
          commandParams:
            interposer: vector
          podSpec:
            containers:
              - image: alpine:latest
                command: ["sh"]
                args:
                  - "-c"
                  - |
                    echo "=== WRAPPER SCRIPT START ==="
                    echo "Custom setup before step execution..."
                    echo ""
                    echo "BUILDKITE_COMMAND: $BUILDKITE_COMMAND"
                    echo ""
                    echo "Now executing BUILDKITE_COMMAND..."
                    echo "---"
                    eval "$BUILDKITE_COMMAND"
                    exit_code=$?
                    echo "---"
                    echo "Step finished with exit code: $exit_code"
                    echo "Custom cleanup after step execution..."
                    echo "=== WRAPPER SCRIPT END ==="
                    exit $exit_code

  - label: ":test_tube: Test 2 - Step command preserved separately"
    command: |
      echo "THIS IS THE ORIGINAL STEP COMMAND"
      echo "From pipeline.yaml"
    agents:
      queue: "kubernetes"
    plugins:
      - kubernetes:
          commandParams:
            interposer: vector
          podSpec:
            containers:
              - image: alpine:latest
                command: ["sh"]
                args:
                  - "-c"
                  - |
                    echo "=== CHECKING ENV VARS ==="
                    echo "BUILDKITE_COMMAND: $BUILDKITE_COMMAND"
                    echo "BUILDKITE_SCRIPT_PATH: $BUILDKITE_SCRIPT_PATH"
                    echo ""
                    echo "NOTE: When podSpec command is set, it REPLACES the step command"
                    echo "The step command from pipeline.yaml is NOT in BUILDKITE_COMMAND"
                    echo "=== END ==="
