steps:
  - label: ":package: Upload Artifact"
    key: "upload"
    command: |
      echo "Uploading test-script.sh as an artifact..."
      ls -la test-script.sh
    artifact_paths: "test-script.sh"
    agents:
      queue: "kubernetes"

  - wait

  - label: ":one: Job 1 - Check What's Cached"
    key: "job1"
    command: |
      echo "Job 1 - Checking what's already in plugins directory from previous builds:"
      ls -la /workspace/plugins/ 2>&1 || echo "No plugins dir yet"
      echo ""
      echo "Looking for any cached plugins:"
      find /workspace/plugins/ -maxdepth 1 -type d 2>&1 | head -20
    agents:
      queue: "kubernetes"

  - wait

  - label: ":two: Job 2 - Download Plugin (Parallel)"
    key: "job2"
    command: |
      echo "Job 2 starting..."
      echo "Downloaded artifact:"
      ls -la test-script.sh 2>&1
      echo ""
      echo "Plugins after download:"
      ls -la /workspace/plugins/ 2>&1
      find /workspace/plugins/ -name "*artifacts*" -type d 2>&1
    plugins:
      - artifacts#v1.9.4:
          download: "test-script.sh"
    agents:
      queue: "kubernetes"

  - label: ":three: Job 3 - Download Plugin (Parallel)"
    key: "job3"
    command: |
      echo "Job 3 starting..."
      echo "Downloaded artifact:"
      ls -la test-script.sh 2>&1
      echo ""
      echo "Plugins after download:"
      ls -la /workspace/plugins/ 2>&1
      find /workspace/plugins/ -name "*artifacts*" -type d 2>&1
    plugins:
      - artifacts#v1.9.4:
          download: "test-script.sh"
    agents:
      queue: "kubernetes"

  - wait

  - label: ":four: Job 4 - Should Reuse Cache (Sequential)"
    key: "job4"
    command: |
      echo "Job 4 starting (should see 'already checked out')..."
      echo "Downloaded artifact:"
      ls -la test-script.sh 2>&1
      echo ""
      echo "Plugins directory:"
      ls -la /workspace/plugins/ 2>&1
      find /workspace/plugins/ -name "*artifacts*" -type d 2>&1
    plugins:
      - artifacts#v1.9.4:
          download: "test-script.sh"
    agents:
      queue: "kubernetes"
