steps:
  - label: "Test 1: Cache plugin first use"
    command: |
      echo "Step 1: First time using cache plugin"
      ls -la /workspace/plugins/ || true
      echo "test-content-$(date +%s)" > test-file.txt
      cat test-file.txt
    agents:
      queue: "kubernetes"
    plugins:
      - cache#v1.8.1:
          backend: fs
          path: test-cache
          manifest: test-file.txt
          restore: file
          save: file
    env:
      BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "/workspace/cache-data"

  - label: "Test 2: Cache plugin second use"
    command: |
      echo "Step 2: Second time using cache plugin (should reuse plugin repo)"
      ls -la /workspace/plugins/
      echo "Looking for cache plugin checkout:"
      find /workspace/plugins/ -name "*cache*" -type d || true
      echo "test-content-$(date +%s)" > test-file.txt
      cat test-file.txt
    agents:
      queue: "kubernetes"
    plugins:
      - cache#v1.8.1:
          backend: fs
          path: test-cache
          manifest: test-file.txt
          restore: file
          save: file
    env:
      BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "/workspace/cache-data"

  - label: "Test 3: Cache plugin third use"
    command: |
      echo "Step 3: Third time using cache plugin (should also reuse plugin repo)"
      ls -la /workspace/plugins/
      echo "Checking if plugin was cloned or reused:"
      find /workspace/plugins/ -name "*cache*" -type d -exec ls -la {} \; || true
    agents:
      queue: "kubernetes"
    plugins:
      - cache#v1.8.1:
          backend: fs
          path: test-cache
          manifest: test-file.txt
          restore: file
          save: file
    env:
      BUILDKITE_PLUGIN_FS_CACHE_FOLDER: "/workspace/cache-data"
