steps:
  - label: ":writing_hand: Write to persistent storage"
    key: "write-test"
    command: |
      echo "Creating test data in persistent storage..."
      mkdir -p /workspace/plugins/test-data
      echo "Test data from job 1 - timestamp: \$(date +%s)" > /workspace/plugins/test-data/persistence-test.txt
      echo "Agent name: \$BUILDKITE_AGENT_NAME" >> /workspace/plugins/test-data/persistence-test.txt
      echo "Job ID: \$BUILDKITE_JOB_ID" >> /workspace/plugins/test-data/persistence-test.txt
      cat /workspace/plugins/test-data/persistence-test.txt
      ls -la /workspace/plugins/test-data/
    agents:
      queue: "kubernetes"

  - wait

  - label: ":mag: Read from persistent storage"
    key: "read-test"
    command: |
      echo "Reading test data from persistent storage..."
      echo "Current agent: \$BUILDKITE_AGENT_NAME"
      echo "---"
      if [ -f /workspace/plugins/test-data/persistence-test.txt ]; then
        echo "SUCCESS: File found in persistent storage!"
        cat /workspace/plugins/test-data/persistence-test.txt
        echo "---"
        echo "Listing all files in plugins directory:"
        find /workspace/plugins -type f
      else
        echo "FAIL: File not found. Storage not persisting."
        exit 1
      fi
    agents:
      queue: "kubernetes"

  - wait

  - label: ":broom: Cleanup test data"
    key: "cleanup-test"
    command: |
      echo "Cleaning up test data..."
      rm -rf /workspace/plugins/test-data
      echo "Cleanup complete"
    agents:
      queue: "kubernetes"
