steps:
  - label: ":one: Job 1 - First Download"
    key: "job1"
    command: |
      echo "Job 1 starting..."
      echo "Checking plugins directory:"
      ls -la /workspace/plugins/ || echo "No plugins dir yet"
      echo "Looking for artifacts plugin:"
      find /workspace/plugins/ -name "*artifacts*" -type d || echo "Not found yet"
    plugins:
      - artifacts#v1.9.4:
          download: "*.txt"
    agents:
      queue: "kubernetes"

  - wait

  - label: ":two: Job 2 - Should Reuse Cache"
    key: "job2"
    command: |
      echo "Job 2 starting..."
      echo "Checking plugins directory:"
      ls -la /workspace/plugins/ || echo "No plugins dir yet"
      echo "Looking for artifacts plugin:"
      find /workspace/plugins/ -name "*artifacts*" -type d || echo "Not found yet"
    plugins:
      - artifacts#v1.9.4:
          download: "*.txt"
    agents:
      queue: "kubernetes"

  - wait

  - label: ":three: Job 3 - Should Also Reuse Cache"
    key: "job3"
    command: |
      echo "Job 3 starting..."
      echo "Checking plugins directory:"
      ls -la /workspace/plugins/ || echo "No plugins dir yet"
      echo "Looking for artifacts plugin:"
      find /workspace/plugins/ -name "*artifacts*" -type d || echo "Not found yet"
    plugins:
      - artifacts#v1.9.4:
          download: "*.txt"
    agents:
      queue: "kubernetes"
