steps:
  - label: ":one: First Job - Check Plugin Paths"
    key: first-job
    command: |
      echo "=== First job - checking plugin paths ==="
      echo "BUILDKITE_PLUGINS_PATH: ${BUILDKITE_PLUGINS_PATH:-not set}"
      echo "BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME: ${BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME:-not set}"
      echo "Agent name: ${BUILDKITE_AGENT_NAME}"
      echo "Job ID: ${BUILDKITE_JOB_ID}"
      echo ""
      echo "Plugin directories:"
      ls -la ${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/ 2>/dev/null || echo "No plugins directory found"
      echo ""
      echo "Checking for monorepo-diff plugin:"
      find ${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/ -name "*monorepo-diff*" -type d 2>/dev/null || echo "Not found"
      echo ""
      echo "Creating test cache file..."
      mkdir -p cache
      echo "Job 1 was here at $(date)" > cache/test-file.txt
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v1.5.0:
          checkout: true
          watch:
            - path: "packages/*"
      - cache#v1.8.1:
          path: "cache"
          restore: pipeline
          save: pipeline
  
  - label: ":two: Second Job - Verify Plugin Sharing"
    key: second-job
    command: |
      echo "=== Second job - verifying plugin sharing ==="
      echo "BUILDKITE_PLUGINS_PATH: ${BUILDKITE_PLUGINS_PATH:-not set}"
      echo "BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME: ${BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME:-not set}"
      echo "Agent name: ${BUILDKITE_AGENT_NAME}"
      echo "Job ID: ${BUILDKITE_JOB_ID}"
      echo ""
      echo "Plugin directories:"
      ls -la ${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/ 2>/dev/null || echo "No plugins directory found"
      echo ""
      echo "Checking for monorepo-diff plugin:"
      find ${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/ -name "*monorepo-diff*" -type d 2>/dev/null || echo "Not found"
      echo ""
      echo "Checking cached file from job 1:"
      if [ -f cache/test-file.txt ]; then
        echo "✅ Cache file found!"
        cat cache/test-file.txt
        echo "Job 2 was here at $(date)" >> cache/test-file.txt
      else
        echo "❌ Cache file not found"
      fi
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v1.5.0:
          checkout: true
          watch:
            - path: "packages/*"
      - cache#v1.8.1:
          path: "cache"
          restore: pipeline
          save: pipeline

  - label: ":three: Third Job - Final Verification"
    key: third-job
    command: |
      echo "=== Third job - final verification ==="
      echo "BUILDKITE_PLUGINS_PATH: ${BUILDKITE_PLUGINS_PATH:-not set}"
      echo "BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME: ${BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME:-not set}"
      echo "Agent name: ${BUILDKITE_AGENT_NAME}"
      echo "Job ID: ${BUILDKITE_JOB_ID}"
      echo ""
      echo "Plugin directories:"
      ls -la ${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/ 2>/dev/null || echo "No plugins directory found"
      echo ""
      echo "All plugin directories (checking if shared or per-agent):"
      find ${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/ -maxdepth 2 -type d 2>/dev/null | head -20
      echo ""
      echo "Checking cached file history:"
      if [ -f cache/test-file.txt ]; then
        echo "✅ Cache file found!"
        cat cache/test-file.txt
      else
        echo "❌ Cache file not found"
      fi
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v1.5.0:
          checkout: true
          watch:
            - path: "packages/*"
      - cache#v1.8.1:
          path: "cache"
          restore: pipeline
          save: pipeline
