steps:
  - label: ":rocket: Job 1 - Download & Lock Plugin"
    key: "job1"
    command: |
      echo "Job 1 starting..."
      echo "Checking for plugin downloads..."
      ls -la /workspace/plugins/ || echo "No plugins dir yet"

      echo "Sleeping for 5 seconds to simulate work..."
      sleep 5

      echo "After work, checking plugins:"
      ls -la /workspace/plugins/

      echo "Looking for lock files:"
      find /workspace/plugins -name "*.clonelockf" -ls
    plugins:
      - docker#v5.11.0:
          image: alpine:latest
    agents:
      queue: "kubernetes"

  - label: ":rocket: Job 2 - Should Wait for Lock"
    key: "job2"
    command: |
      echo "Job 2 starting..."
      echo "Checking for plugin downloads..."
      ls -la /workspace/plugins/ || echo "No plugins dir yet"

      echo "Sleeping for 5 seconds to simulate work..."
      sleep 5

      echo "After work, checking plugins:"
      ls -la /workspace/plugins/

      echo "Looking for lock files:"
      find /workspace/plugins -name "*.clonelockf" -ls
    plugins:
      - docker#v5.11.0:
          image: alpine:latest
    agents:
      queue: "kubernetes"

  - label: ":rocket: Job 3 - Should Reuse Cached Plugin"
    key: "job3"
    command: |
      echo "Job 3 starting..."
      echo "Checking for plugin downloads..."
      ls -la /workspace/plugins/ || echo "No plugins dir yet"

      echo "Sleeping for 5 seconds to simulate work..."
      sleep 5

      echo "After work, checking plugins:"
      ls -la /workspace/plugins/

      echo "Looking for lock files:"
      find /workspace/plugins -name "*.clonelockf" -ls
    plugins:
      - docker#v5.11.0:
          image: alpine:latest
    agents:
      queue: "kubernetes"
