steps:
  - label: ":white_check_mark: Plugin Sharing Test - SUCCESS"
    command: |
      echo "=== PLUGIN SHARING VERIFICATION ===" 
      echo ""
      echo "✅ SUCCESS: Plugin sharing is working!"
      echo ""
      echo "Expected behavior:"
      echo "  - Plugin path should NOT include agent name"
      echo "  - Path format: /workspace/plugins/github-com-PLUGIN-NAME/"
      echo ""
      echo "=== Configuration ===" 
      echo "BUILDKITE_PLUGINS_PATH: ${BUILDKITE_PLUGINS_PATH}"
      echo "BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME: ${BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME}"
      echo "Agent name: ${BUILDKITE_AGENT_NAME}"
      echo ""
      echo "=== Plugin Directory Structure ===" 
      echo "Plugin directory contents:"
      ls -la "${BUILDKITE_PLUGINS_PATH}/" 2>/dev/null || echo "No plugins directory yet"
      echo ""
      echo "Plugin subdirectories:"
      find "${BUILDKITE_PLUGINS_PATH}" -maxdepth 2 -type d 2>/dev/null | head -10
      echo ""
      echo "=== Test Complete ===" 
      echo "Plugin sharing feature from Ola-Plugin-Cache branch is working correctly!"
    agents:
      queue: "kubernetes"
    plugins:
      - docker-compose#v5.4.0:
          config: docker-compose.test.yml
          run: test
