steps:
  - key: test-checkout-skip-behavior
    label: ":test_tube: Test Checkout Skip with Plugin"
    commands:
      - echo "=== Testing checkout skip behavior ==="
      - echo "Current working directory:"
      - pwd
      - echo "Directory contents (should be empty since checkout is skipped):"
      - ls -la
      - echo "But the plugin should still be available and working!"
    agents:
      queue: kubernetes
    retry:
      manual: true
      automatic:
        - limit: 2
          exit_status: -1
    plugins:
      - kubernetes:
          checkout:
            skip: true  # This skips source repo checkout
          podSpec:
            serviceAccountName: deployer-manager
            containers:
            - image: bitnami/kubectl:latest

  - label: "Deploy Nginx to Kubernetes"
    commands:
      - echo "Deploying Nginx to Kubernetes"
      - kubectl apply -f k8s/configmap.yaml
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
      - kubectl rollout status deployment/nginx-deployment --timeout=300s
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deployer-manager  # Use your new SA
            containers:
            - image: bitnami/kubectl:latest