steps:
  - label: ":test_tube: Test Custom PodSpec Command"
    agents:
      queue: "kubernetes"
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
                command:
                  - |
                    echo "=== CUSTOM ENTRYPOINT SCRIPT ==="
                    echo "BUILDKITE_COMMAND: $BUILDKITE_COMMAND"
                    echo "BUILDKITE_SCRIPT_PATH: $BUILDKITE_SCRIPT_PATH"
                    echo "=== ENV VARS ==="
                    env | grep -i buildkite | sort
                    echo "=== END ==="
