steps:
  - label: ":mag: Check Agent Version and Config"
    command: |
      echo "=== Agent Information ===" 
      echo "Agent version:"
      buildkite-agent --version || echo "Could not get agent version"
      echo ""
      echo "=== Environment Variables Related to Plugins ===" 
      env | grep -i plugin | sort || echo "No plugin-related env vars"
      echo ""
      echo "=== Plugin Path Structure ===" 
      echo "BUILDKITE_PLUGINS_PATH: ${BUILDKITE_PLUGINS_PATH:-not set}"
      echo "BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME: ${BUILDKITE_PLUGINS_PATH_INCLUDES_AGENT_NAME:-not set}"
      echo "BUILDKITE_PLUGINS_LOCK_TIMEOUT: ${BUILDKITE_PLUGINS_LOCK_TIMEOUT:-not set}"
      echo ""
      echo "Agent name: ${BUILDKITE_AGENT_NAME}"
      echo "Job ID: ${BUILDKITE_JOB_ID}"
      echo ""
      echo "=== Actual Plugin Directory Contents ===" 
      if [ -d "${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}" ]; then
        ls -la "${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}/" | head -20
        echo ""
        echo "Looking for agent-name subdirectories:"
        ls -d "${BUILDKITE_PLUGINS_PATH:-/workspace/plugins}"/*/ 2>/dev/null | head -10
      else
        echo "Plugin directory does not exist yet"
      fi
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v1.5.0:
          diff: "HEAD~1"
          log_level: "debug"
