steps:
  - label: "Deploy Nginx to Kubernetes"
    command: echo "Deploying Nginx to Kubernetes"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          manifests:
            - ../k8s/deployment.yaml
            - ../k8s/service-account.yaml
            - ../k8s/service.yaml
          wait: true
          waitTimeout: 300
          waitInterval: 5
