steps:
  - label: "Deploy Nginx to Kubernetes (with checkout skip - should fail)"
    commands:
      - echo "Deploying Nginx to Kubernetes"
      - echo "Current directory contents:"
      - ls -la
      - echo "Attempting to apply manifests (should fail):"
      - kubectl apply -f k8s/configmap.yaml
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml
      - kubectl rollout status deployment/nginx-deployment --timeout=300s
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          checkout:
            skip: true  # This will cause the deployment to fail
          podSpec:
            serviceAccountName: deployer-manager
            containers:
            - image: bitnami/kubectl:latest