agents:
  queue: mac

steps:
  - label: Build
    command: echo 'Build step.'

  - label: Test
    command: echo 'Test step.'
    depends_on: "~"

  - wait

  - label: Deploy
    command: echo 'Deploy step.'
    depends_on: "~"
