steps:
  - label: "Deploy Nginx to Kubernetes"
    commands:
      - echo "Deploying Nginx to Kubernetes"
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service-account.yaml  
      - kubectl apply -f k8s/service.yaml
      - kubectl rollout status deployment/nginx --timeout=300s
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
            - image: bitnami/kubectl:latest  # Container with kubectl