agents:
  queue: "mac"
  os: "macos-14"

steps:
  - label: ":pipeline: Build"
    command: "echo 'Hello from Buildkite! Merge queue test. Main branch update.'"

  - label: ":test_tube: Test"
    command: "echo 'Running main branch tests...' && sleep 1 && echo 'Tests complete.'"
    depends_on: "~"
    env:
      TEST_ENV: "merge-queue"

  - wait

  - label: ":rocket: Deploy"
    command: "echo 'Deploying from main branch...' && sleep 1 && echo 'Deploy complete.'"
    depends_on: "~"
    env:
      DEPLOY_ENV: "merge-queue"
