steps:
  - label: "Plugin paths test"
    command: |
      ls -la "${BUILDKITE_PLUGINS_PATH}/"
      find "${BUILDKITE_PLUGINS_PATH}" -maxdepth 1 -type d
    agents:
      queue: "kubernetes"
    plugins:
      - shellcheck#v1.3.0:
          files: "**/*.sh"
      - artifacts#v1.9.4:
          download: "*.log"
