steps:
  # Test: Both step command AND podSpec command defined
  # Question: What ends up in BUILDKITE_COMMAND?
  - label: ":mag: PROOF - Both step and podSpec command"
    command: |
      echo "THIS IS THE STEP COMMAND"
      echo "If you see this in BUILDKITE_COMMAND, step command was preserved"
    agents:
      queue: "kubernetes"
    plugins:
      - kubernetes:
          commandParams:
            interposer: vector
          podSpec:
            containers:
              - image: alpine:latest
                command: ["sh"]
                args:
                  - "-c"
                  - |
                    echo "=== PROOF TEST ==="
                    echo ""
                    echo "This script is the podSpec command."
                    echo ""
                    echo "BUILDKITE_COMMAND value:"
                    echo "---"
                    echo "$BUILDKITE_COMMAND"
                    echo "---"
                    echo ""
                    echo "BUILDKITE_SCRIPT_PATH value:"
                    echo "$BUILDKITE_SCRIPT_PATH"
                    echo ""
                    echo "If BUILDKITE_COMMAND contains 'THIS IS THE STEP COMMAND',"
                    echo "then the step command was preserved."
                    echo ""
                    echo "If BUILDKITE_COMMAND contains this script (podSpec command),"
                    echo "then the step command was replaced."
                    echo "=== END PROOF ==="
