steps:
  - label: "First job - clone plugin"
    command: |
      echo "First job - plugin should be cloned"
      ls -la "${BUILDKITE_PLUGINS_PATH}/" || echo "Plugins dir empty"
    agents:
      queue: "kubernetes"
    plugins:
      - shellcheck#v1.3.0:
          files: "doesnotexist.sh"
    
  - label: "Second job - reuse plugin"
    command: |
      echo "Second job - plugin should be reused if same agent"
      ls -la "${BUILDKITE_PLUGINS_PATH}/"
    agents:
      queue: "kubernetes"
    plugins:
      - shellcheck#v1.3.0:
          files: "doesnotexist.sh"

  - label: "Third job - reuse plugin"  
    command: |
      echo "Third job - plugin should be reused if same agent"
      ls -la "${BUILDKITE_PLUGINS_PATH}/"
    agents:
      queue: "kubernetes"
    plugins:
      - shellcheck#v1.3.0:
          files: "doesnotexist.sh"
