steps:
  - label: "Deploy Nginx to Kubernetes"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: k8s.gcr.io/kubectl:v1.28.0
                command: "kubectl apply -f ../k8s/ && echo '\nWaiting for deployment to be ready...' && kubectl rollout status deployment/nginx-deployment"
