steps:
  - label: "Deploy Nginx to Kubernetes"
    command: |
      kubectl apply -f ../k8s/
      echo "\nWaiting for deployment to be ready..."
      kubectl rollout status deployment/nginx-deployment
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
podSpec:
          containers:
            - image: buildkite/agent:alpine-k8s

