steps:
  - label: ":test_tube: Test monorepo-diff retry + cache"
    agents:
      queue: kubernetes
    plugins:
      - Mykematt/monorepo-diff#Ola-retry-logic:
          binary_cache_path: /workspace/plugins/monorepo-cache
          diff: "git diff --name-only HEAD~1"
          log_level: "debug"
          watch:
            - path: ".buildkite/"
              config:
                command: "echo 'Changes detected in .buildkite/'"

  - label: ":arrow_up: Upload BuildKit + ECR Test"
    command: "buildkite-agent pipeline upload .buildkite/buildkit-ecr-test.yml"
    agents:
      queue: mac
