steps:
  - label: "Deploy Nginx to Kubernetes"
    commands:
      # Create namespace if it doesn't exist
      - kubectl create namespace default || true
      
      # Apply resources in default namespace
      - kubectl apply -f k8s/deployment.yaml -n default
      - kubectl apply -f k8s/service-account.yaml -n default
      - kubectl apply -f k8s/service.yaml -n default
      
      # Wait for deployment to be ready
      - kubectl rollout status deployment/nginx -n default --timeout=300s
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          podSpec:
            containers:
            - image: bitnami/kubectl:latest
          