steps:
  - label: ":monorepo: Test Plugin Checkout Fix"
    key: test-plugin-checkout
    command: echo "Testing plugin checkout behavior with binary downloads"
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v2.2.0:
          checkout: true
          watch:
            - path: "packages/*"
      - docker-compose#v3.0.0:
          build: .
          config: docker-compose.yml
      - cache#v1.0.0:
          path: "cache"
          restore: true
          save: true

  - label: ":docker: Build and Test"
    command: |
      echo "Build completed successfully!"
      echo "Plugins were checked out and binaries downloaded correctly."
      echo "This proves the fix for plugin checkout behavior is working."
    agents:
      queue: "kubernetes"
