steps:
  - label: ":test_tube: monorepo-diff Run 1"
    agents:
      queue: kubernetes
    plugins:
      - buildkite-plugins/monorepo-diff-buildkite-plugin#v1.5.2:
          diff: "git diff --name-only HEAD~1"
          log_level: "debug"
          watch:
            - path: ".buildkite/"
              config:
                command: "echo 'Run 1 complete'"

  - label: ":mag: Debug storage (after Run 1)"
    agents:
      queue: kubernetes
    command: |
      df -Th | grep -E "(plugins|workspace|Filesystem)"
      echo ""
      find /workspace/plugins -maxdepth 2 -mindepth 2 2>/dev/null | head -20 || echo "No plugins found"

  - wait

  - label: ":test_tube: monorepo-diff Run 2"
    agents:
      queue: kubernetes
    plugins:
      - buildkite-plugins/monorepo-diff-buildkite-plugin#v1.5.2:
          diff: "git diff --name-only HEAD~1"
          log_level: "debug"
          watch:
            - path: ".buildkite/"
              config:
                command: "echo 'Run 2 complete'"

  - label: ":mag: Debug storage (after Run 2)"
    agents:
      queue: kubernetes
    command: |
      df -Th | grep -E "(plugins|workspace|Filesystem)"
      echo ""
      find /workspace/plugins -maxdepth 2 -mindepth 2 2>/dev/null | head -20 || echo "No plugins found"
