steps:
  - label: ":rocket: Job 1 - First plugin use"
    key: "first download"
    command: |
      echo "Job 1 starting"
      echo "Plugin location:"
      ls -la /workspace/plugins/ 2>&1 || echo "No plugins dir yet"
      echo "Success!"
    agents:
      queue: "kubernetes"
    plugins:
      - docker#v5.11.0:
          image: "alpine:latest"

  - wait 
  
  - label: ":zap: Job 2 - Should reuse plugin"
    key: "second no download"
    depends_on: "first download"
    command: |
      echo "Job 2 starting"
      echo "Plugin should be reused:"
      ls -la /workspace/plugins/
      echo "Success!"
    agents:
      queue: "kubernetes"
    plugins:
      - docker#v5.11.0:
          image: "alpine:latest"

  - wait 
  
  - label: ":fire: Job 3 - Should also reuse plugin"
    key: "third no download"
    depends_on: "second no download"
    command: |
      echo "Job 3 starting"
      echo "Checking plugin reuse:"
      find /workspace/plugins/ -name "*docker*" -type d | head -5
      echo "Success!"
    agents:
      queue: "kubernetes"
    plugins:
      - docker#v5.11.0:
          image: "alpine:latest"
