steps:
  - label: ":test_tube: monorepo-diff Run 1"
    agents:
      queue: kubernetes
    plugins:
      - Mykematt/monorepo-diff#Ola-retry-logic:
          diff: "git diff --name-only HEAD~1"
          log_level: "debug"
          watch:
            - path: ".buildkite/"
              config:
                command: "echo 'Run 1 complete'"

  - wait

  - label: ":test_tube: monorepo-diff Run 2"
    agents:
      queue: kubernetes
    plugins:
      - Mykematt/monorepo-diff#Ola-retry-logic:
          diff: "git diff --name-only HEAD~1"
          log_level: "debug"
          watch:
            - path: ".buildkite/"
              config:
                command: "echo 'Run 2 complete'"
