steps:
  - label: ":rocket: Job 1 - Monorepo diff plugin"
    command: |
      echo "Job 1 starting"
      echo "Plugin location:"
      ls -la /workspace/plugins/ 2>&1 || echo "No plugins dir yet"
      echo "Checking monorepo plugin:"
      find /workspace/plugins/ -name "*monorepo*" -type d 2>&1 || echo "Plugin not found"
      echo "Success!"
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v2.6.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "."
              config:
                command: "echo 'monorepo plugin executed'"

  - label: ":rocket: Job 2 - Monorepo diff plugin"
    command: |
      echo "Job 2 starting"
      echo "Plugin location:"
      ls -la /workspace/plugins/ 2>&1 || echo "No plugins dir yet"
      echo "Checking monorepo plugin:"
      find /workspace/plugins/ -name "*monorepo*" -type d 2>&1 || echo "Plugin not found"
      echo "Success!"
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v2.6.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "."
              config:
                command: "echo 'monorepo plugin executed'"

  - label: ":rocket: Job 3 - Monorepo diff plugin"
    command: |
      echo "Job 3 starting"
      echo "Plugin location:"
      ls -la /workspace/plugins/ 2>&1 || echo "No plugins dir yet"
      echo "Checking monorepo plugin:"
      find /workspace/plugins/ -name "*monorepo*" -type d 2>&1 || echo "Plugin not found"
      echo "Success!"
    agents:
      queue: "kubernetes"
    plugins:
      - monorepo-diff#v2.6.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "."
              config:
                command: "echo 'monorepo plugin executed'"
