# Test pipeline to verify branch annotations on K8s pods
# This will add the buildkite.io/branch annotation to the pod

steps:
  - label: "🔍 Test Branch Annotation"
    command: |
      echo "Testing branch annotation on Kubernetes pod"
      echo "Current branch: $BUILDKITE_BRANCH"
      echo "Build number: $BUILDKITE_BUILD_NUMBER"
      echo "Pipeline: $BUILDKITE_PIPELINE_SLUG"
      
      # If you have kubectl access from within the pod, you could verify:
      # kubectl describe pod $HOSTNAME
    agents:
      queue: kubernetes  # Adjust to your queue name
    plugins:
      - kubernetes:
          metadata:
            annotations:
              buildkite.io/branch: "${BUILDKITE_BRANCH}"
              buildkite.io/build-number: "${BUILDKITE_BUILD_NUMBER}"
              buildkite.io/pipeline: "${BUILDKITE_PIPELINE_SLUG}"
              # Add any other annotations you want to test
              otel.trace/enabled: "true"
