agents:
  queue: "mac"

steps:
  - input: "Select stuff"
    fields:
      - select: "Options"
        multiple: true
        key: "options"
        options:
          - label: "option1"
            value: "option1"
          - label: "option2"
            value: "option2"
          - label: "option3"
            value: "option3"
          - label: "option4"
            value: "option4"
          - label: "option5"
            value: "option5"
  - wait: ~
  - commands: buildkite-agent meta-data get options
