agents:
  queue: kubernetes

steps:
  - label: "🚀 Test Plugin - Real EKS Deploy (Kubernetes Plugin)"
    key: "test-plugin-real-eks-deploy-kubernetes-plugin"
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deployer-manager
            containers:
            - image: dtzar/helm-kubectl:latest
      - https://github.com/mykematt/deployment-helm-chart-buildkite-plugin.git#main:
          mode: deploy
          release: buildkite-helm-test
          chart: oci://registry-1.docker.io/bitnamicharts/nginx
          namespace: default
          set:
            - image.tag=1.29.1-debian-12-r0
            - replicaCount=2
            - service.type=ClusterIP
          timeout: 600s
          wait: true
          atomic: true
          create_namespace: true

  - label: "✅ Verify Deployment (Kubernetes Plugin)"
    command: |
      echo 'Verifying deployment status...'
      helm list -n default
      helm status buildkite-helm-test -n default
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deployer-manager
            containers:
            - image: dtzar/helm-kubectl:latest
    depends_on: "test-plugin-real-eks-deploy-kubernetes-plugin"

  - block: "🤔 Test Rollback?"
    key: "rollback-gate"
    depends_on: "verify-deployment"

  - label: "🔄 Test Plugin - Real Rollback (Kubernetes Plugin)"
    depends_on: "rollback-gate"
    plugins:
      - kubernetes:
          podSpec:
            serviceAccountName: deployer-manager
            containers:
            - image: dtzar/helm-kubectl:latest
      - https://github.com/mykematt/deployment-helm-chart-buildkite-plugin.git#main:
          mode: rollback
          release: buildkite-helm-test
          namespace: default
