agents:
  queue: kubernetes

steps:
  - label: "🧪 Test Plugin - Missing Parameters"
    key: "test-missing-params"
    command: "echo 'Testing parameter validation...'"
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0
              image: dtzar/helm-kubectl:latest
      - https://github.com/mykematt/deployment-helm-chart-buildkite-plugin.git#main:
          # All parameters present - should succeed
          mode: deploy
          release: test-release
          chart: nginx

  - label: "🧪 Test Plugin - Invalid Mode"
    key: "test-invalid-mode"
    depends_on: "test-missing-params"
    command: "echo 'Testing invalid mode...'"
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0
              image: dtzar/helm-kubectl:latest
      - https://github.com/mykematt/deployment-helm-chart-buildkite-plugin.git#main:
          mode: invalid
          release: test-release
          chart: nginx

  - label: "🚀 Test Plugin - Real EKS Deploy (Kubernetes Plugin)"
    key: "test-plugin-real-eks-deploy-kubernetes-plugin"
    depends_on: "test-invalid-mode"
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0
              image: dtzar/helm-kubectl:latest
      - https://github.com/mykematt/deployment-helm-chart-buildkite-plugin.git#main:
          mode: deploy
          release: buildkite-helm-test
          chart: oci://registry-1.docker.io/bitnamicharts/nginx
          namespace: buildkite-helm-test
          set:
            - image.tag=1.21-alpine
            - replicaCount=2
            - service.type=ClusterIP
          timeout: 600s
          wait: true
          atomic: true
          create_namespace: true

  - label: "✅ Verify Deployment (Kubernetes Plugin)"
    command: |
      echo 'Verifying deployment status...'
      helm list -n buildkite-helm-test
      helm status buildkite-helm-test -n buildkite-helm-test
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0
              image: dtzar/helm-kubectl:latest
    depends_on: "test-plugin-real-eks-deploy-kubernetes-plugin"

  - block: "🤔 Test Rollback?"
    key: "rollback-gate"
    depends_on: "verify-deployment"

  - label: "🔄 Test Plugin - Real Rollback (Kubernetes Plugin)"
    depends_on: "rollback-gate"
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0
              image: dtzar/helm-kubectl:latest
      - https://github.com/mykematt/deployment-helm-chart-buildkite-plugin.git#main:
          mode: rollback
          release: buildkite-helm-test
          namespace: buildkite-helm-test
