# deployment-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa
  namespace: buildkite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services", "serviceaccounts", "pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-sa
  namespace: buildkite
roleRef:
  kind: Role
  name: deployment-role
  apiGroup: rbac.authorization.k8s.io